// field-type.enum.ts
export enum FieldTypeEnum {
  SOFTWARE_ENGINEER = "Software Engineer",
  FRONTEND_DEVELOPER = "Frontend Developer",
  BACKEND_DEVELOPER = "Backend Developer",
  FULLSTACK_DEVELOPER = "Fullstack Developer",
  UX_DESIGNER = "UX Designer",
  UI_DESIGNER = "UI Designer",
  PRODUCT_DESIGNER = "Product Designer",
  DATA_SCIENTIST = "Data Scientist",
  DEVOPS_ENGINEER = "DevOps Engineer",
  PRODUCT_MANAGER = "Product Manager",
  DIGITAL_MARKETER = "Digital Marketer",
  CONTENT_CREATOR = "Content Creator",
  GRAPHIC_DESIGNER = "Graphic Designer",
  MOTION_DESIGNER = "Motion Designer",
  CYBERSECURITY_SPECIALIST = "Cybersecurity Specialist",
  GAME_DEVELOPER = "Game Developer",
  MOBILE_DEVELOPER = "Mobile Developer",
  AI_ENGINEER = "AI Engineer",
  CLOUD_ARCHITECT = "Cloud Architect",
  TECHNICAL_WRITER = "Technical Writer",
  OTHER = "Other",
}
